#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="enkaceli_db")]
public partial class dcDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void InserttblAyarlar(tblAyarlar instance);
  partial void UpdatetblAyarlar(tblAyarlar instance);
  partial void DeletetblAyarlar(tblAyarlar instance);
  partial void InserttblMusteriler(tblMusteriler instance);
  partial void UpdatetblMusteriler(tblMusteriler instance);
  partial void DeletetblMusteriler(tblMusteriler instance);
  partial void InserttblCariHareket(tblCariHareket instance);
  partial void UpdatetblCariHareket(tblCariHareket instance);
  partial void DeletetblCariHareket(tblCariHareket instance);
  #endregion
	
	public dcDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["enkaceli_dbConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public dcDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public dcDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public dcDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public dcDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<tblAyarlar> tblAyarlars
	{
		get
		{
			return this.GetTable<tblAyarlar>();
		}
	}
	
	public System.Data.Linq.Table<tblMusteriler> tblMusterilers
	{
		get
		{
			return this.GetTable<tblMusteriler>();
		}
	}
	
	public System.Data.Linq.Table<tblCariHareket> tblCariHarekets
	{
		get
		{
			return this.GetTable<tblCariHareket>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblAyarlar")]
public partial class tblAyarlar : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id;
	
	private string _k_adi;
	
	private string _sifre;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onk_adiChanging(string value);
    partial void Onk_adiChanged();
    partial void OnsifreChanging(string value);
    partial void OnsifreChanged();
    #endregion
	
	public tblAyarlar()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this.OnidChanging(value);
				this.SendPropertyChanging();
				this._id = value;
				this.SendPropertyChanged("id");
				this.OnidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_k_adi", DbType="VarChar(500)")]
	public string k_adi
	{
		get
		{
			return this._k_adi;
		}
		set
		{
			if ((this._k_adi != value))
			{
				this.Onk_adiChanging(value);
				this.SendPropertyChanging();
				this._k_adi = value;
				this.SendPropertyChanged("k_adi");
				this.Onk_adiChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sifre", DbType="VarChar(500)")]
	public string sifre
	{
		get
		{
			return this._sifre;
		}
		set
		{
			if ((this._sifre != value))
			{
				this.OnsifreChanging(value);
				this.SendPropertyChanging();
				this._sifre = value;
				this.SendPropertyChanged("sifre");
				this.OnsifreChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblMusteriler")]
public partial class tblMusteriler : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _m_id;
	
	private string _m_ad;
	
	private string _m_soyad;
	
	private string _m_telefon;
	
	private string _m_ceptel;
	
	private string _m_mail;
	
	private string _m_tc;
	
	private string _m_adres;
	
	private string _m_aciklama;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onm_idChanging(int value);
    partial void Onm_idChanged();
    partial void Onm_adChanging(string value);
    partial void Onm_adChanged();
    partial void Onm_soyadChanging(string value);
    partial void Onm_soyadChanged();
    partial void Onm_telefonChanging(string value);
    partial void Onm_telefonChanged();
    partial void Onm_ceptelChanging(string value);
    partial void Onm_ceptelChanged();
    partial void Onm_mailChanging(string value);
    partial void Onm_mailChanged();
    partial void Onm_tcChanging(string value);
    partial void Onm_tcChanged();
    partial void Onm_adresChanging(string value);
    partial void Onm_adresChanged();
    partial void Onm_aciklamaChanging(string value);
    partial void Onm_aciklamaChanged();
    #endregion
	
	public tblMusteriler()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_m_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int m_id
	{
		get
		{
			return this._m_id;
		}
		set
		{
			if ((this._m_id != value))
			{
				this.Onm_idChanging(value);
				this.SendPropertyChanging();
				this._m_id = value;
				this.SendPropertyChanged("m_id");
				this.Onm_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_m_ad", DbType="VarChar(500)")]
	public string m_ad
	{
		get
		{
			return this._m_ad;
		}
		set
		{
			if ((this._m_ad != value))
			{
				this.Onm_adChanging(value);
				this.SendPropertyChanging();
				this._m_ad = value;
				this.SendPropertyChanged("m_ad");
				this.Onm_adChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_m_soyad", DbType="VarChar(500)")]
	public string m_soyad
	{
		get
		{
			return this._m_soyad;
		}
		set
		{
			if ((this._m_soyad != value))
			{
				this.Onm_soyadChanging(value);
				this.SendPropertyChanging();
				this._m_soyad = value;
				this.SendPropertyChanged("m_soyad");
				this.Onm_soyadChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_m_telefon", DbType="VarChar(500)")]
	public string m_telefon
	{
		get
		{
			return this._m_telefon;
		}
		set
		{
			if ((this._m_telefon != value))
			{
				this.Onm_telefonChanging(value);
				this.SendPropertyChanging();
				this._m_telefon = value;
				this.SendPropertyChanged("m_telefon");
				this.Onm_telefonChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_m_ceptel", DbType="VarChar(500)")]
	public string m_ceptel
	{
		get
		{
			return this._m_ceptel;
		}
		set
		{
			if ((this._m_ceptel != value))
			{
				this.Onm_ceptelChanging(value);
				this.SendPropertyChanging();
				this._m_ceptel = value;
				this.SendPropertyChanged("m_ceptel");
				this.Onm_ceptelChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_m_mail", DbType="VarChar(500)")]
	public string m_mail
	{
		get
		{
			return this._m_mail;
		}
		set
		{
			if ((this._m_mail != value))
			{
				this.Onm_mailChanging(value);
				this.SendPropertyChanging();
				this._m_mail = value;
				this.SendPropertyChanged("m_mail");
				this.Onm_mailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_m_tc", DbType="VarChar(500)")]
	public string m_tc
	{
		get
		{
			return this._m_tc;
		}
		set
		{
			if ((this._m_tc != value))
			{
				this.Onm_tcChanging(value);
				this.SendPropertyChanging();
				this._m_tc = value;
				this.SendPropertyChanged("m_tc");
				this.Onm_tcChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_m_adres", DbType="VarChar(500)")]
	public string m_adres
	{
		get
		{
			return this._m_adres;
		}
		set
		{
			if ((this._m_adres != value))
			{
				this.Onm_adresChanging(value);
				this.SendPropertyChanging();
				this._m_adres = value;
				this.SendPropertyChanged("m_adres");
				this.Onm_adresChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_m_aciklama", DbType="VarChar(500)")]
	public string m_aciklama
	{
		get
		{
			return this._m_aciklama;
		}
		set
		{
			if ((this._m_aciklama != value))
			{
				this.Onm_aciklamaChanging(value);
				this.SendPropertyChanging();
				this._m_aciklama = value;
				this.SendPropertyChanged("m_aciklama");
				this.Onm_aciklamaChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblCariHareket")]
public partial class tblCariHareket : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _ch_id;
	
	private string _ch_urun;
	
	private System.Nullable<double> _ch_tutar;
	
	private string _ch_tarih;
	
	private string _ch_aciklama;
	
	private System.Nullable<int> _m_id;
	
	private System.Nullable<int> _ch_harekettipi;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onch_idChanging(int value);
    partial void Onch_idChanged();
    partial void Onch_urunChanging(string value);
    partial void Onch_urunChanged();
    partial void Onch_tutarChanging(System.Nullable<double> value);
    partial void Onch_tutarChanged();
    partial void Onch_tarihChanging(string value);
    partial void Onch_tarihChanged();
    partial void Onch_aciklamaChanging(string value);
    partial void Onch_aciklamaChanged();
    partial void Onm_idChanging(System.Nullable<int> value);
    partial void Onm_idChanged();
    partial void Onch_harekettipiChanging(System.Nullable<int> value);
    partial void Onch_harekettipiChanged();
    #endregion
	
	public tblCariHareket()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ch_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int ch_id
	{
		get
		{
			return this._ch_id;
		}
		set
		{
			if ((this._ch_id != value))
			{
				this.Onch_idChanging(value);
				this.SendPropertyChanging();
				this._ch_id = value;
				this.SendPropertyChanged("ch_id");
				this.Onch_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ch_urun", DbType="VarChar(500)")]
	public string ch_urun
	{
		get
		{
			return this._ch_urun;
		}
		set
		{
			if ((this._ch_urun != value))
			{
				this.Onch_urunChanging(value);
				this.SendPropertyChanging();
				this._ch_urun = value;
				this.SendPropertyChanged("ch_urun");
				this.Onch_urunChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ch_tutar", DbType="Float")]
	public System.Nullable<double> ch_tutar
	{
		get
		{
			return this._ch_tutar;
		}
		set
		{
			if ((this._ch_tutar != value))
			{
				this.Onch_tutarChanging(value);
				this.SendPropertyChanging();
				this._ch_tutar = value;
				this.SendPropertyChanged("ch_tutar");
				this.Onch_tutarChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ch_tarih", DbType="VarChar(500)")]
	public string ch_tarih
	{
		get
		{
			return this._ch_tarih;
		}
		set
		{
			if ((this._ch_tarih != value))
			{
				this.Onch_tarihChanging(value);
				this.SendPropertyChanging();
				this._ch_tarih = value;
				this.SendPropertyChanged("ch_tarih");
				this.Onch_tarihChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ch_aciklama", DbType="VarChar(500)")]
	public string ch_aciklama
	{
		get
		{
			return this._ch_aciklama;
		}
		set
		{
			if ((this._ch_aciklama != value))
			{
				this.Onch_aciklamaChanging(value);
				this.SendPropertyChanging();
				this._ch_aciklama = value;
				this.SendPropertyChanged("ch_aciklama");
				this.Onch_aciklamaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_m_id", DbType="Int")]
	public System.Nullable<int> m_id
	{
		get
		{
			return this._m_id;
		}
		set
		{
			if ((this._m_id != value))
			{
				this.Onm_idChanging(value);
				this.SendPropertyChanging();
				this._m_id = value;
				this.SendPropertyChanged("m_id");
				this.Onm_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ch_harekettipi", DbType="Int")]
	public System.Nullable<int> ch_harekettipi
	{
		get
		{
			return this._ch_harekettipi;
		}
		set
		{
			if ((this._ch_harekettipi != value))
			{
				this.Onch_harekettipiChanging(value);
				this.SendPropertyChanging();
				this._ch_harekettipi = value;
				this.SendPropertyChanged("ch_harekettipi");
				this.Onch_harekettipiChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
